### ISSUE TITLE
Wrong path loaded for %PROGRAMFILES% un action.ini

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/unimacro#1]
try and edit a file with notepad++, here is the actions.ini section
```
[bringup npeepee]
name = notepad++.exe
path = %PROGRAMFILES%\notepad++
```

unimacro looks in "C:\Program Files (x86)\notepad++" instead of 
expanding the ProgramFiles environment to "C:\Program Files".

here is the full traceback.

```
openFileDefault: C:\Users\Doug\OneDrive\family\doug\work in progress\voice projects\Unimacro\_folders.py (type: <class 'str'>, mode: edit, openWith: None)
Traceback (most recent call last):
  File "C:\Users\Doug\OneDrive\family\doug\work in progress\voice projects\Unimacro\natlinkutilsbj.py", line 1224, in resultsCallback
    self.__inherited.resultsCallback(self, wordsAndNums, resObj)
  File "C:\Users\Doug\OneDrive\family\doug\work in progress\voice projects\Unimacro\natlinkutilsbj.py", line 671, in resultsCallback
    self.__inherited.resultsCallback(self, wordsAndNums, resObj)
  File "C:\Users\Doug\OneDrive\family\doug\work in progress\voice projects\natlink\MacroSystem\core\natlinkutils.py", line 855, in resultsCallback
    self.callRuleResultsFunctions(seqsAndRules, fullResults)
  File "C:\Users\Doug\OneDrive\family\doug\work in progress\voice projects\natlink\MacroSystem\core\natlinkutils.py", line 880, in callRuleResultsFunctions
    self.callIfExists( 'gotResults_'+ruleName, (ruleWords, fullResults) )
  File "C:\Users\Doug\OneDrive\family\doug\work in progress\voice projects\natlink\MacroSystem\core\natlinkutils.py", line 378, in callIfExists
    return func(*argList)
  File "C:\Users\Doug\OneDrive\family\doug\work in progress\voice projects\Unimacro\_control.py", line 592, in gotResults_edit
    self.openFileDefault(filename, mode="edit", name='edit grammar %s'% gramName)
  File "C:\Users\Doug\OneDrive\family\doug\work in progress\voice projects\Unimacro\natlinkutilsbj.py", line 2584, in openFileDefault
    return UnimacroBringUp(mode, filename)
  File "C:\Users\Doug\OneDrive\family\doug\work in progress\voice projects\Unimacro\actions.py", line 2079, in UnimacroBringUp
    raise IOError('invalid path for  app %s: %s (expanded: %s)'% (app, appPath, appPath2))
OSError: invalid path for  app npeepee: %PROGRAMFILES%\notepad++ (expanded: C:\Program Files (x86)\notepad++)
```

**Comment by quintijn** [comment]
the ++ of Notepad++ has always been a vulnerable point. Can you point out where notepad++.exe is located?

**Comment by dougransom** [comment]
C:\Program Files\Notepad++\notepad++.exe

I think it is not the ++ though, but that the code is looking in the wrong folder?

**Comment by quintijn** [comment]
Please try %PROGRAMW6432%    This one should point to: C:\Program Files

But... I also tried, untested, no good example at hand, to automatically try this variable if PROGRAMFILES fails. 

Please try and see if it works. Just pushed my changes.

**Comment by dougransom** [comment]
That seemed to work.
