### ISSUE TITLE
Komodo Defaults Baffle Users

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/unimacro#30]
We need to fix the current config file  **and** have a process to make sure we don't have komodo or notepad++ or any editor than notepad as an option in any default config file, otherwise users have no idea what is going on.  Probably can add this to a unit test or something because I am sure this keeps happening even after we change defaults to notepad.
```
===Please edit this file by calling the command "edit control"
skipping unchanged bad module: _vocola_main
skipping unchanged bad module: _vocola_main
grammar: control: <inigr: control>
openFileDefault: C:\Users\doug\OneDrive\doug\Unimacro\enx_inifiles\_control.ini (mode: edit, openWith: None)
Traceback (most recent call last):
  File "C:\Users\doug\AppData\Local\Programs\Python\Python310-32\lib\site-packages\unimacro\natlinkutilsbj.py", line 1096, in resultsCallback
    self.__inherited.resultsCallback(self, wordsAndNums, resObj)
  File "C:\Users\doug\AppData\Local\Programs\Python\Python310-32\lib\site-packages\unimacro\natlinkutilsbj.py", line 557, in resultsCallback
    self.__inherited.resultsCallback(self, wordsAndNums, resObj)
  File "C:\Users\doug\AppData\Local\Programs\Python\Python310-32\lib\site-packages\natlinkcore\natlinkutils.py", line 986, in resultsCallback
    self.callRuleResultsFunctions(seqsAndRules, fullResults)
  File "C:\Users\doug\AppData\Local\Programs\Python\Python310-32\lib\site-packages\natlinkcore\natlinkutils.py", line 1011, in callRuleResultsFunctions
    self.callIfExists( 'gotResults_'+ruleName, (ruleWords, fullResults) )
  File "C:\Users\doug\AppData\Local\Programs\Python\Python310-32\lib\site-packages\natlinkcore\natlinkutils.py", line 367, in callIfExists
    return func(*argList)
  File "C:\Users\doug\AppData\Local\Programs\Python\Python310-32\lib\site-packages\unimacro\_control.py", line 609, in gotResults_edit
    grammar.editInifile()
  File "C:\Users\doug\AppData\Local\Programs\Python\Python310-32\lib\site-packages\unimacro\natlinkutilsbj.py", line 2026, in editInifile
    self.openFileDefault(inifile, mode="edit")
  File "C:\Users\doug\AppData\Local\Programs\Python\Python310-32\lib\site-packages\unimacro\natlinkutilsbj.py", line 2507, in openFileDefault
    return UnimacroBringUp(mode, filename)
  File "C:\Users\doug\AppData\Local\Programs\Python\Python310-32\lib\site-packages\dtactions\unimacro\unimacroactions.py", line 2050, in UnimacroBringUp
    raise OSError('invalid path for  app %s: %s (expanded: %s)'% (app, appPath, appPath2))
OSError: invalid path for  app komodo: C:\Program Files (x86)\ActiveState Komodo IDE 12\komodo.exe (expanded: C:\Program Files (x86)\ActiveState Komodo IDE 12\komodo.exe)

```

**Comment by dougransom** [comment]
The specification of komodo may be in code, not in a config file.

**Comment by quintijn** [comment]
I will remove them, but this is in dtactions.

**Comment by quintijn** [comment]
I think I did remove these...
