### ISSUE TITLE
ClickByVoice , unimacrotest  fails topchild

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/unimacro#35]
`skipping unchanged loaded module: _unimacrotest
Traceback (most recent call last):
  File "C:\Users\doug\AppData\Local\Programs\Python\Python310-32\lib\site-packages\unimacro\natlinkutilsbj.py", line 548, in beginCallback
    self.callIfExists("gotBegin", (moduleInfo,) )
  File "C:\Users\doug\code\dt\natlinkcore\src\natlinkcore\natlinkutils.py", line 367, in callIfExists
    return func(*argList)
  File "C:\Users\doug\AppData\Local\Programs\Python\Python310-32\lib\site-packages\unimacro\unimacrogrammars\_clickbyvoice.py", line 97, in gotBegin
    if progInfo.topchild == 'child':
AttributeError: 'ProgInfo' object has no attribute 'topchild'. Did you mean: 'toporchild'?`

**Comment by dougransom** [comment]
I think this is happening in many grammars

leDefault: C:\Users\doug\OneDrive\doug\Unimacro\enx_inifiles\_folders.ini (mode: edit, openWith: None)
filepath unimacroactions: |""C:\Users\doug\OneDrive\doug\Unimacro\enx_inifiles\_folders.ini""|
on_begin_callback called with: moduleInfo: ('C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe', 'ClickByVoice , unimacrotest fails topchild · Issue #35 · dictation-toolbox/unimacro and 5 more pages - Personal - Microsoft\u200b Edge', 397332)
Traceback (most recent call last):
  File "C:\Users\doug\AppData\Local\Programs\Python\Python310-32\lib\site-packages\unimacro\natlinkutilsbj.py", line 548, in beginCallback
    self.callIfExists("gotBegin", (moduleInfo,) )
  File "C:\Users\doug\code\dt\natlinkcore\src\natlinkcore\natlinkutils.py", line 367, in callIfExists
    return func(*argList)
  File "C:\Users\doug\AppData\Local\Programs\Python\Python310-32\lib\site-packages\unimacro\unimacrogrammars\_clickbyvoice.py", line 97, in gotBegin
    if progInfo.topchild == 'child':
AttributeError: 'ProgInfo' object has no attribute 'topchild'. Did you mean: 'toporchild'?
on_change_callback called with: "mic", "off"
on_change_callback called with: "mic", "on"

**Comment by quintijn** [comment]
if fixed, will be in installer at next release
