### ISSUE TITLE
Komodo is default text editor.

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/unimacro#59]
This keeps happening, how can we prevent it?   It *is* possible this is a vestige from an old unimacro install on my PC.  Installed natlink and unimacro 4.1.6 today.

`O:natlink.unimacro.control:---now starting other Unimacro grammars:
openFileDefault: C:\Users\Doug\unimacro-202310\enx_inifiles\_control.ini (mode: edit, openWith: None)
Traceback (most recent call last):
  File "C:\Users\Doug\AppData\Roaming\Python\Python310-32\site-packages\unimacro\natlinkutilsbj.py", line 888, in resultsCallback
    self.__inherited.resultsCallback(self, wordsAndNums, resObj)
  File "C:\Users\Doug\AppData\Roaming\Python\Python310-32\site-packages\unimacro\natlinkutilsbj.py", line 492, in resultsCallback
    self.__inherited.resultsCallback(self, wordsAndNums, resObj)
  File "C:\Program Files (x86)\Python310-32\lib\site-packages\natlinkcore\natlinkutils.py", line 1012, in resultsCallback
    self.callRuleResultsFunctions(seqsAndRules, fullResults)
  File "C:\Program Files (x86)\Python310-32\lib\site-packages\natlinkcore\natlinkutils.py", line 1037, in callRuleResultsFunctions
    self.callIfExists( 'gotResults_'+ruleName, (ruleWords, fullResults) )
  File "C:\Program Files (x86)\Python310-32\lib\site-packages\natlinkcore\natlinkutils.py", line 390, in callIfExists
    return func(*argList)
  File "C:\Users\Doug\AppData\Roaming\Python\Python310-32\site-packages\unimacro\_control.py", line 598, in gotResults_edit
    grammar.editInifile()
  File "C:\Users\Doug\AppData\Roaming\Python\Python310-32\site-packages\unimacro\natlinkutilsbj.py", line 1830, in editInifile
    self.openFileDefault(inifile, mode="edit")
  File "C:\Users\Doug\AppData\Roaming\Python\Python310-32\site-packages\unimacro\natlinkutilsbj.py", line 2307, in openFileDefault
    return UnimacroBringUp(mode, filename)
  File "C:\Program Files (x86)\Python310-32\lib\site-packages\dtactions\unimacro\unimacroactions.py", line 2052, in UnimacroBringUp
    raise OSError('invalid path for  app %s: %s (expanded: %s)'% (app, appPath, appPath2))
OSError: invalid path for  app komodo: C:\Program Files (x86)\ActiveState Komodo IDE 12\komodo.exe (expanded: C:\Program Files (x86)\ActiveState Komodo IDE 12\komodo.exe)
`

**Comment by quintijn** [comment]
The simple way is "edit folders", and remove the settings where  "komodo" appears. 

I will clean up the sample ini file versions.

**Comment by dougransom** [comment]
Edit folders may not work as it will create the problem above.   

I propose to remove all mention of Komodo in any source files, if there are any mentions.  

Write some sort of process to check that notepad is the default on new install/upgrade of unimacro or dtactions and some sort of list we check to make sure anything other than notepad is not the default.  It always must be notepad on a new install, and probably we should have a checkbox in natlinkconfg_gui to reset to notepad as well.   

I think part of the issue perhaps is actions.ini isn't being copied. 

Branch unimacro_summer24 btw.

**Comment by quintijn** [comment]
The actions mechanism is ported from unimacro to dtactions. the ini file actions.ini is now named unimacroactions.ini.

The module unimacroactions.py in dtactions/unimacro should handle this, but this is not all working.

I want to try to first reproducs the error above, via pytest, but there is some testing in (...)\unimacro\unimacro_test\BringupTest.py. 

In any case, unimacroactions.py should be copied from a sample file in the dtactions repo into the natlink_settingsdir (where natlink.ini also is). I would propose dtactions/unimacroactions.ini.

When files change, by the user or in updates of dtactions, this will be not easy to tackle. 

Let us first try to have this all ported to dtactions.

Consequence: when unimacro is also installed, and the control grammar on, you can call "edit actions" or "edit unimacro actions" in order to inspect and edit this ini file.

When unimacro is NOT installed and used, the unimacroactions are still available, for example via vocola, but calling the unimacroactions.ini file cannot directly be done by a voice command.

**Comment by dougransom** [comment]
Interesting.  If dragonfly also had a use for this, should it be called "unimacro actions" or instead "global actions"?
