### ISSUE TITLE
Show Active Grammars, Show All Grammars Broken

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/unimacro#7]
This appears to be because pywin32 command line arguments appear to be ignored.
https://github.com/mhammond/pywin32/issues/1620

In the meantime any code calling pythonwin.exe will not work.

**Comment by dougransom** [comment]
pywin32 have addressed the problem (though i haven't tried the fix), probably easiest to way until there is a new release of pywin32 we can install with pip.

**Comment by dougransom** [comment]
``I tried an updated version of pywin32.   It was able to start (I think) but then there is a trace back in natlink:

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python38-32\lib\site-packages\Pythonwin\pywin\framework\startup.py", line 62, in <module>
    __import__(moduleName)
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\Unimacro\src\unimacro\BrowseGrammarApp.py", line 54, in <module>
    from natlinkutils import *
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\natlink\MacroSystem\core\natlinkutils.py", line 89, in <module>
    import natlinkmain
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\natlink\MacroSystem\core\natlinkmain.py", line 1010, in <module>
    start_natlink()
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\natlink\MacroSystem\core\natlinkmain.py", line 955, in start_natlink
    changeCallback('user', natlink.getCurrentUser())
natlink.NatError: Calling getCurrentUser is not allowed before calling natConnect`

**Comment by dougransom** [comment]
You can download can updated pywin32 from https://github.com/mhammond/pywin32/pull/1622/checks  download the artifacts, extract the files from zip, they are prebuilt binaries.

pip install --force-reinstall .\pywin32-300.1-cp38-cp38-win32.whl

**Comment by quintijn** [comment]
pythonwin is not used any more. pywin32 is! Doug, can we close this issue?

**Comment by quintijn** [comment]
this can become a new issue together with https://github.com/dictation-toolbox/unimacro/issues/33
I close this one...
